poster:
  image: reddec/apcsrv
  volumes_from:
    - collector
  environment:
    TARGET: "$TARGET"
    APC_NAME: "$NAME"
    APC_HOST: "$APC_HOST"
    APC_PORT: "$APC_PORT"
    INTERVAL: "$INTERVAL"
