.catalog:
  name: apcupsd
  version: 1
  uuid: apcupsd1
  minimum_rancher_version: v0.46.0
  questions:
    - variable: APC_HOST
      label: IP address of APC UPS
      description: |
        Remote address of APC UPS which will be used for SNMP connection
      required: true
      type: string
    - variable: TARGET
      label: Target endpoint used for HTTP POST request
      description: |
        This param used as url of remote server which accepts POST request.
      required: true
      type: string
    - variable: NAME
      label: Unique name for APC UPS
      description: |
        APC UPS unique name may be used as ID for later
      required: false
      type: string
    - variable: APC_PORT
      label: SNMP port of APC UPS
      description: Remote UDP port used for SNMP connection
      type: int
      required: true
      default: 161
    - variable: INTERVAL
      label: Interval in seconds between checks
      description: Check each N seconds for status of APC UPS over SNMP
      type: int
      required: true
      default: 3
